export const spotsList = [
  {
    city: 'Lisbon',
    state: 'Lisbon',
    country: 'Portugal',
    timezone: 'Europe/Lisbon',
    citySlug: 'lisbon',
    countrySlug: 'portugal',
    lat: 38.694086,
    lon: -9.146118,
  },
  {
    city: 'Santander',
    state: 'Cantabria',
    country: 'Spain',
    timezone: 'Europe/Madrid',
    citySlug: 'santander',
    countrySlug: 'spain',
    lat: 43.468309,
    lon: -3.819549,
  },
  {
    city: 'Los Angels',
    state: 'California',
    country: 'United States of America',
    timezone: 'America/Los_Angeles',
    citySlug: 'los_angels',
    countrySlug: 'united_state_of_america',
    lat: 33.711438,
    lon: -118.283851,
  },
  {
    city: 'Coolangatta',
    state: 'Queensland',
    country: 'Australia',
    timezone: 'Australia/Queensland',
    citySlug: 'coolangatta',
    countrySlug: 'australia',
    lat: -28.166430,
    lon: 153.533499,
  },
  {
    city: 'Pecatu',
    state: 'Bali',
    country: 'Indonesia',
    timezone: ' Asia/Makassar',
    citySlug: 'pecatu',
    countrySlug: 'indonesia',
    lat: -8.814836,
    lon: 115.088389,
  },
];
