---
format_version: '5'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
trigger_map:
- push_branch: master
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.11: {}
    - nvm@1.2.1:
        inputs:
        - node_version: 8.11.1
    - yarn@0.0.7:
        inputs:
        - command: install
    - script@1.1.5:
        title: Lint and Test
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # debug log
            set -x

            npm run lint
            npm test
    - heroku-deploy@0.9.3:
        title: Deploy site
    - slack@2.7.3:
        inputs:
        - channel: "$SLACK_CHANNEL"
        - text: The app is live
        - emoji: ":merman:"
        - title_link: "$SITE_URL"
        - webhook_url: "$SLACK_WEBHOOK_URL"